### ISSUE TITLE
PyImGui compatibility with PyGame 2.0.0

### ISSUE THREAD

**Issue by jpmanson** [swistakm/pyimgui#181]
I'm trying to run this example with the just released PyGame 2.0.0: https://github.com/swistakm/pyimgui/blob/master/doc/examples/integrations_pygame.py

And I get this error:
pygame 2.0.0 (SDL 2.0.12, python 3.7.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/Users/Shared/Development/integrations_pygame.py", line 63, in <module>
    main()
  File "/Users/Shared/Development/integrations_pygame.py", line 31, in main
    imgui.new_frame()
  File "imgui/core.pyx", line 1823, in imgui.core.new_frame
imgui.core.ImGuiError: ImGui assertion error (g.IO.KeyMap[n] >= -1 && g.IO.KeyMap[n] < IM_ARRAYSIZE(g.IO.KeysDown) && "io.KeyMap[] contains an out of bound value (need to be 0..512, or -1 for unmapped key)") at imgui-cpp/imgui.cpp:3097

Process finished with exit code 1

--------------------------------------------------------------------------------------------

The error is raised when executing **imgui.new_frame()**. It seems that the KeyMap it is not initialized OK , and then the assertion error is thrown. 
The example runs without any problem using Pygame 1.9.6

Any idea in how to fix this, and make pyimgui compatible with pygame 2.0.0?
Thanks!

**Comment by jpmanson** [comment]
...more information:
My operating system is MacOS High Sierra 10.13.6

At runtime, this constants has values > 512, so the mentioned assertion is fired in imgui.cpp.

        key_map[imgui.KEY_LEFT_ARROW] = pygame.K_LEFT       # pygame.K_LEFT=1073741904
        key_map[imgui.KEY_RIGHT_ARROW] = pygame.K_RIGHT     # pygame.K_RIGHT=1073741903
        key_map[imgui.KEY_UP_ARROW] = pygame.K_UP           # pygame.K_UP=1073741906
        key_map[imgui.KEY_DOWN_ARROW] = pygame.K_DOWN       # pygame.K_DOWN=1073741905
        key_map[imgui.KEY_PAGE_UP] = pygame.K_PAGEUP        # pygame.K_PAGEUP=1073741899
        key_map[imgui.KEY_PAGE_DOWN] = pygame.K_PAGEDOWN    # pygame.K_PAGEDOWN=1073741902
        key_map[imgui.KEY_HOME] = pygame.K_HOME             # pygame.K_HOME=1073741898
        key_map[imgui.KEY_END] = pygame.K_END               # pygame.K_END=1073741901

**Comment by pdietrich** [comment]
Same problem on Windows 10:
```
pygame 2.0.0 (SDL 2.0.12, python 3.6.1)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File ".\ardj.py", line 205, in <module>
    main_pygame()
  File ".\ardj.py", line 108, in main_pygame
    imgui.new_frame()
  File "imgui\core.pyx", line 1823, in imgui.core.new_frame
imgui.core.ImGuiError: ImGui assertion error (g.IO.KeyMap[n] >= -1 && g.IO.KeyMap[n] < IM_ARRAYSIZE(g.IO.KeysDown) && "io.KeyMap[] contains an out of bound value (need to be 0..512, or -1 for unmapped key)") at imgui-cpp/imgui.cpp:3097
```

**Comment by KinoxKlark** [comment]
This should be fixed in #192. Imgui limits the key_map values to -1 or 0..512; thus, values like 1073741904 is clearly out of bounds. The same problem happened when I added new input keys to `pysdl2` version. Fix here was easy: go to scancode instead of keycode. I am not used to PyGame, so I couldn't find any way to easily use scancode. Thus I had to implement a custom remapping, which leads to a small overhead. If you know a better way or if there is any problem let me know.

**Comment by tayler6000** [comment]
This will be fixed by #244 but until then, [here's the workaround](https://github.com/pyimgui/pyimgui/issues/210#issuecomment-1036571753)
