### ISSUE TITLE
pyimgui/doc/examples/integrations_pygame.py cannot run!

### ISSUE THREAD

**Issue by lkklkklkkj** [swistakm/pyimgui#210]
Here is error message:

```
pygame 2.0.0 (SDL 2.0.12, python 3.8.7)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "integrations_pygame.py", line 64, in <module>
    main()
  File "integrations_pygame.py", line 31, in main
    imgui.new_frame()
  File "imgui\core.pyx", line 1824, in imgui.core.new_frame
imgui.core.ImGuiError: ImGui assertion error (g.IO.KeyMap[n] >= -1 && g.IO.KeyMap[n] < IM_ARRAYSIZE(g.IO.KeysDown) &
o.KeyMap[] contains an out of bound value (need to be 0..512, or -1 for unmapped key)") at imgui-cpp/imgui.cpp:3097
```
And this is my pip freeze:
```
imgui==1.3.0
pygame==2.0.0
PyOpenGL==3.1.5
```

Did I miss something ?

**Comment by learn-more** [comment]
Same bug here, seems to be an issue with this example.
Host: Windows 10 Build 19041

**Comment by KinoxKlark** [comment]
Correct me if I am wrong, but I think this is the same problem as in #181. This should have been fixed in #192. As a quick explanation: ImGui `IO.KeyMap` array can only deal with values between -1 and 512. Unfortunately, PyGame keycodes values can be greater than 512 (e.g. `pygame.K_LEFT=1073741904`). This is fixed using scancode instead of keycode in most integration code, but I couldn't figure out a way to do it in PyGame. Thus I had to implement a custom remapping, which leads to a small overhead. Any suggestion to improve that is welcome.

**Comment by learn-more** [comment]
> Correct me if I am wrong, but I think this is the same problem as in #181. This should have been fixed in #192. As a quick explanation: ImGui `IO.KeyMap` array can only deal with values between -1 and 512. Unfortunately, PyGame keycodes values can be greater than 512 (e.g. `pygame.K_LEFT=1073741904`). This is fixed using scancode instead of keycode in most integration code, but I couldn't figure out a way to do it in PyGame. Thus I had to implement a custom remapping, which leads to a small overhead. Any suggestion to improve that is welcome.

This seems to be a duplicate issue, yes.

**Comment by DenisTome** [comment]
The problem still persists with same outcomes.

**Comment by Mau-MD** [comment]
Same here, it doesn't run the example code.

**Comment by redsett** [comment]
I'm getting the same error as well.

**Comment by KinoxKlark** [comment]
Hello, this should be fixed in the next major release that is currently in preparation. No update has been done for a while due to project management issues. A future minor release should come soon, followed by the next major release that will update pyimgui to a more recent version of dearimgui and fix several issues of this kind.

In the meantime you can try and test the next major release using the appropriate branch, i.e. ```dev/version-2-0```. Any feedback would be appreciated :)

**Comment by jtiai** [comment]
Apparently this issue is still open and persistent. Was there ever a release that fixed this?

**Comment by KinoxKlark** [comment]
Unfortunately no, I didn't have time to pull together the major release yet. This has been fixed in the `dev/version-2.0` branch from which you can install the library. It should be stable enough to be used. I still need to release it but I won't have time until mid-January.

If for whatever reason you can't or don't want to manually install from the dev branch, you can easily patch it yourself. Pyimgui comes with examples of integration like `pygame` but it is not bound to any of them. You can make your own integration. The simpler would be to reuse the one from the `dev` branch. For further details, please refer to my comment in #254. Feel free to ask if you encounter difficulties.

**Comment by nhammond129** [comment]
For anyone looking for easy copy-paste solutions, you can install the `dev/version-2.0` branch with
```sh
pip install git+https://github.com/pyimgui/pyimgui.git@dev/version-2.0
```
(generically: `pip install git+<URL>@<BRANCH>`)

**Comment by TechStudent10** [comment]
> For anyone looking for easy copy-paste solutions, you can install the `dev/version-2.0` branch with
> 
> ```shell
> pip install git+https://github.com/pyimgui/pyimgui.git@dev/version-2.0
> ```
> 
> (generically: `pip install git+<URL>@<BRANCH>`)

This worked perfectly! Thank you!
