### ISSUE TITLE
OpenGL.GL import error on macOS Big Sur 

### ISSUE THREAD

**Issue by swistakm** [swistakm/pyimgui#212]
Traceback:
```
Traceback (most recent call last):
  File "/Users/swistakm/dev/pyimgui/.venv/lib/python3.9/site-packages/OpenGL/platform/darwin.py", line 35, in GL
    return ctypesloader.loadLibrary(
  File "/Users/swistakm/dev/pyimgui/.venv/lib/python3.9/site-packages/OpenGL/platform/ctypesloader.py", line 36, in loadLibrary
    return _loadLibraryWindows(dllType, name, mode)
  File "/Users/swistakm/dev/pyimgui/.venv/lib/python3.9/site-packages/OpenGL/platform/ctypesloader.py", line 89, in _loadLibraryWindows
    return dllType( name, mode )
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ('dlopen(OpenGL, 10): image not found', 'OpenGL', None)

During handling of the above exception, another exception occurred:
```

I've seen some references stating that this could be fixed in latest Python release but I tested in 3.9.1 and it didn't work. There's also no fix available in PyOpenGL. Anyway, this can be definitely hacked-around so probably we can provide a gl import kludge in the `imgui._compat` module until (if ever) this gets fixed upstream.

**Comment by pbuckner** [comment]
The problem is due to Big Sur now caching libraries. Python OpenGL attempts to locate its shared library using ctypes.util.find_library()

find_library() actually looks on the filesystem, but Big Sur doesn't put it there, so find_library() fails. The bug is in ctypes support for Big Sur. (https://bugs.python.org/issue41100)

Fixes have been made in python code, but the build configuration fails to build it properly & the necessary code isn't compiled in. (If you manually compile your version of Python, I'm told it works great -- the version available to download from python.org does not.)

Continues to fail for 3.9.2.

It's an easy, though manual patch to OpenGL to hard-coded the location, but patching it within imgui might be tough.

(site-packages/OpenGL/platfomr/ctypesload.py, line 80, change 
`
fullName = util.find_library( name )
`
 -to-
`
fullName = '/System/Library/Frameworks/OpenGL.framework/OpenGL'
`
