### ISSUE TITLE
Cannot 'reload' imgui shared library in embedded C

### ISSUE THREAD

**Issue by pbuckner** [swistakm/pyimgui#225]
python 'reloading' is risky with respect to shared libraries. While it appears you can reload a simple python script which imports imgui, doing this within the context of an embedded python doesn't work: _py_vertext_buffer_vertext_pos_offset become None and the second import fails.

See attached 20-line c file "embedded_reload.c".

I import both 'socket' and 'imgui' twice. Note that 'socket' succeeds, but 'imgui' fails on second attempt. I picked socket module as it (like imgui) import _socket shared library... so we know it's "possible", but I don't know why one works and the other does not. 

Resulting output is similar to:
```
$ ./a.out                                                                                                                                           
socket loaded: 140683525758304                                                                                                                      
imgui loaded: 140683525771408                                                                                                                       
socket loaded: 140683525450704                                                                                                                      
Traceback (most recent call last):                                                                                                                  
  File "<string>", line 5, in <module>                                                                                                              
  File "/Volumes/Red1/code/pyimgui/imgui/__init__.py", line 17, in <module>                                                                         
    VERTEX_BUFFER_POS_OFFSET = extra._py_vertex_buffer_vertex_pos_offset()                                                                                
TypeError: 'NoneType' object is not callable                                                                                                        
```

Tested on both windows and mac, I think both instances were with python3.9.

I've tried changing the imgui python scripts in case the problem was related to `from imgui._imgui import *` and `from imgui import _imgui` but that doesn't seem to change the problem. On second load, the first executable line

```
VERTEX_BUFFER_POS_OFFST = extra.vertex_buffer_vertex_pos_offset()
```
fail: vertex_buffer_vertex_pos_offset is None (that is, defined, but None) so is not callable.

[embedded_reload.c.txt](https://github.com/swistakm/pyimgui/files/6290559/embedded_reload.c.txt)

**Comment by learn-more** [comment]
On windows, when looking at loaded modules, neither the sockets nor imgui are actually unloaded in that step. (the .dll files)

**Comment by pbuckner** [comment]
The dll are probably not unloaded (I'll take your word for it), but socket is able to reload or re-initialize anyway the symbols associated with its shared library.  (Or, is my example code working for you?)

imgui appears to reload core shared library, but the symbols are None (Nothing special about ``vertex_buffer_vertex_pos_offset``: all symbols are none .. core.ALWAYS for example.

I don't know if it's related to using cython or how to approach the problem, but being able to reload within embedded would be huge. Any ideas?

**Comment by learn-more** [comment]
> The dll are probably not unloaded (I'll take your word for it), but socket is able to reload or re-initialize anyway the symbols associated with its shared library. (Or, is my example code working for you?)
> 
> imgui appears to reload core shared library, but the symbols are None (Nothing special about `vertex_buffer_vertex_pos_offset`: all symbols are none .. core.ALWAYS for example.
> 
> I don't know if it's related to using cython or how to approach the problem, but being able to reload within embedded would be huge. Any ideas?

Same behavior for me.
When looking in the generated code, there is a `core.cpp` file of roughly 3.8 MB (generated cython stuff):
There is a huge function __pyx_pymod_exec_core(...), this registers objects / types.
My working theory is that this function has some state...

**Comment by pbuckner** [comment]
I'll move forward assuming it's a cython thing and look into pyx_pymod_exec_core. Not the highest priority for me... yet. Thanks.

**Comment by learn-more** [comment]
You could try to define `CYTHON_PEP489_MULTI_PHASE_INIT` to `0`

**Comment by learn-more** [comment]
So basically, I think you need to open a bug or PR on Cython indeed.
One possible option would be to run python in a host process, where you can cycle the entire process,
or use cython's [pyximport.install(reload_support=True](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#arguments)

**Comment by pbuckner** [comment]
Thanks for investigating.

<sigh> CYTHON_PEP489_MULTI_PHASE_INIT=0 will result in a crash on reload, so that's no good.

If I enable 'generate_cleanup_code', I can get a callback when imgui.core is deallocated, (See https://stackoverflow.com/questions/54408210/run-cython-code-when-extension-module-gets-garbage-collected) but within that code, I don't see anything actually useful that I can call there to "force" deallocation.

**Comment by learn-more** [comment]
> Thanks for investigating.
> 
> CYTHON_PEP489_MULTI_PHASE_INIT=0 will result in a crash on reload, so that's no good.
> 
> If I enable 'generate_cleanup_code', I can get a callback when imgui.core is deallocated, (See https://stackoverflow.com/questions/54408210/run-cython-code-when-extension-module-gets-garbage-collected) but within that code, I don't see anything actually useful that I can call there to "force" deallocation.

That callback is called at random before or after global objects are cleaned up, so you cannot safely delete the module pointer there.
An additional problem is that this module pointer is not exposed outside of the generated `core.cpp`
