### ISSUE TITLE
Unknown compiler directives

### ISSUE THREAD

**Issue by stuaxo** [swistakm/pyimgui#37]
Hi,
   I was trying to compile pyimggui, but got the errors below.

OS:  Ubuntu 17.04 64 bit.
Python: 2.7

```
$ make build
Bootstrapping project environment ...
git submodule update --init
Submodule 'imgui-cpp' (https://github.com/ocornut/imgui.git) registered for path 'imgui-cpp'
Cloning into '/mnt/data/home/stu/projects/external/pyimgui/imgui-cpp'...
Submodule path 'imgui-cpp': checked out 'adb85d800d70d3ddc4548f0e8f184eede4568034'
pip install -r doc/requirements-dev.txt
Requirement already satisfied: Cython in /mnt/data/home/stu/.virtualenvs/tmp-5b770036a307de45/lib/python2.7/site-packages (from -r doc/requirements-dev.txt (line 1))
Collecting PyOpenGL (from -r doc/requirements-dev.txt (line 2))
  Downloading PyOpenGL-3.1.0.tar.gz (1.2MB)
    100% |████████████████████████████████| 1.2MB 1.1MB/s 
Collecting glfw (from -r doc/requirements-dev.txt (line 3))
  Downloading glfw-1.4.0.tar.gz
Requirement already satisfied: wheel in /mnt/data/home/stu/.virtualenvs/tmp-5b770036a307de45/lib/python2.7/site-packages (from -r doc/requirements-dev.txt (line 4))
Collecting click (from -r doc/requirements-dev.txt (line 5))
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 5.3MB/s 
Building wheels for collected packages: PyOpenGL, glfw
  Running setup.py bdist_wheel for PyOpenGL ... done
  Stored in directory: /home/stu/.cache/pip/wheels/1c/17/50/f69d63e0a8169fb890f5a167817a73391be85d30e86fd29504
  Running setup.py bdist_wheel for glfw ... done
  Stored in directory: /home/stu/.cache/pip/wheels/8f/14/0a/b191d11fbbab2b5dc4fa090cf37540465f920af5fab87a1fb0
Successfully built PyOpenGL glfw
Installing collected packages: PyOpenGL, glfw, click
Successfully installed PyOpenGL-3.1.0 click-6.7 glfw-1.4.0
_CYTHONIZE_WITH_COVERAGE=1 python -m pip install -e . -v
Converted retries value: Retry(total=5, connect=None, read=None, redirect=None) -> Retry(total=Retry(total=5, connect=None, read=None, redirect=None), connect=None, read=None, redirect=None)
Converted retries value: Retry(total=5, connect=None, read=None, redirect=None) -> Retry(total=Retry(total=5, connect=None, read=None, redirect=None), connect=None, read=None, redirect=None)
Obtaining file:///mnt/data/home/stu/projects/external/pyimgui
  Running setup.py (path:/mnt/data/home/stu/projects/external/pyimgui/setup.py) egg_info for package from file:///mnt/data/home/stu/projects/external/pyimgui
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/data/home/stu/projects/external/pyimgui/setup.py", line 96, in <module>
        ], compiler_directives=cythonize_opts, gdb_debug=True),
      File "/mnt/data/home/stu/.virtualenvs/tmp-5b770036a307de45/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 886, in cythonize
        c_options = CompilationOptions(**options)
      File "/mnt/data/home/stu/.virtualenvs/tmp-5b770036a307de45/local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 568, in __init__
        raise ValueError(message)
    ValueError: got unknown compiler directives: gdb_debug, build_inplace
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /mnt/data/home/stu/projects/external/pyimgui/

```

**Comment by swistakm** [comment]
Oh, I will try to take closer look this week. Could you give list of all package versions in your virtualenv (`pip freeze`)?

**Comment by stuaxo** [comment]
```
$ pip freeze
Cython==0.26
pkg-resources==0.0.0
```

**Comment by swistakm** [comment]
@stuaxo, sorry it took so long. It seems that I have misused the `compiler_directives` argument of `cythonize()` function in `setup.py`. Cython was bit more forgiving in `<0.26` but this have changes in latest release. Thank you for report. It should work now without any problems.

**Comment by stuaxo** [comment]
Looks like setup.py might need tweaking too (tested in py 2.7 venv):

```
python setup.py install
Traceback (most recent call last):
  File "setup.py", line 97, in <module>
    ], compiler_directives=compiler_directives, **cythonize_opts),
  File "/mnt/data/home/stu/.virtualenvs/tmp-9176e541bd1cd401/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 886, in cythonize
    c_options = CompilationOptions(**options)
  File "/mnt/data/home/stu/.virtualenvs/tmp-9176e541bd1cd401/local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 561, in __init__
    directives = dict(options['compiler_directives'])  # copy mutable field
TypeError: 'NoneType' object is not iterable

```

**Comment by swistakm** [comment]
Oh seems like a really dumb mistake :), probably there should empty list instead on None. I'll take a look at this during the weekend because I'm currently afk. Feel free to reopen. If you will be able to fix it before me I'll be happy to review a PR :)

Michał Jaworski

Dnia 04.08.2017 o godz. 17:29 Stuart Axon <notifications@github.com> napisał(a):

**Comment by connorjak** [comment]
I think I am having similar issues building on Windows. This is the only google result for `_CYTHONIZE_WITH_COVERAGE`.

```
(env) PS C:\Users\me\Documents\Github\pyimgui> make build
_CYTHONIZE_WITH_COVERAGE=1 python -m pip install -e . -v
'_CYTHONIZE_WITH_COVERAGE' is not recognized as an internal or external command,
operable program or batch file.
make: *** [build] Error 1
(env) PS C:\Users\me\Documents\Github\pyimgui>
```

**Comment by stuaxo** [comment]
It looks like you are on windows with powershell, I seem to recall environment variables differently in powershell:

```shell
$env:_CYTHONIZE_WITH_COVERAGE=1
python -m pip install -e. - v
```

**Comment by connorjak** [comment]
Ok, that seemed to be the right syntax. Here's what I get when I run `python ci/completion.py -o README.md with-pxd imgui/cimgui.pxd`:

```
(env) PS C:\Users\conno\Documents\Github\pyimgui> python ci/completion.py -o README.md with-pxd imgui/cimgui.pxd
Traceback (most recent call last):
  File "ci/completion.py", line 108, in <module>
    cli(obj={})
  File "C:\Users\conno\Documents\Github\pyimgui\env\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\conno\Documents\Github\pyimgui\env\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\conno\Documents\Github\pyimgui\env\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\conno\Documents\Github\pyimgui\env\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\conno\Documents\Github\pyimgui\env\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\conno\Documents\Github\pyimgui\env\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "ci/completion.py", line 53, in with_pxd
    output(done_count, all_count, ctx.obj['badge_output'])
  File "ci/completion.py", line 84, in output
    float(done_count)/all_count * 100,
ZeroDivisionError: float division by zero
```
When I run `py.test` (after pip installing from the testing requirements):
```
(env) PS C:\Users\conno\Documents\Github\pyimgui> py.test
====================================================== test session starts =======================================================
platform win32 -- Python 3.8.2, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: C:\Users\conno\Documents\Github\pyimgui, configfile: setup.cfg
collected 0 items / 1 error

============================================================= ERRORS =============================================================
_________________________________________________ ERROR collecting test session __________________________________________________
env\lib\site-packages\pluggy\hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
env\lib\site-packages\pluggy\manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
env\lib\site-packages\pluggy\manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
conftest.py:147: in pytest_collect_file
    return SphinxDoc(path, parent)
env\lib\site-packages\_pytest\nodes.py:95: in __call__
    warnings.warn(NODE_USE_FROM_PARENT.format(name=self.__name__), stacklevel=2)
E   pytest.PytestDeprecationWarning: Direct construction of SphinxDoc has been deprecated, please use SphinxDoc.from_parent.
E   See https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent for more details.
==================================================== short test summary info =====================================================
ERROR  - pytest.PytestDeprecationWarning: Direct construction of SphinxDoc has been deprecated, please use SphinxDoc.from_parent.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================== 1 error in 0.26s ========================================================
```

By the way, I have been able to develop on the package just fine with `python -m pip install -e . -v` for rebuilding.
