### ISSUE TITLE
Cython 0.28.* compatibility

### ISSUE THREAD

**Issue by swistakm** [swistakm/pyimgui#55]
Project does not build on Cython==0.28.* probably due to some changes in typing:

```
$ pip install -e .
Obtaining file:///Users/swistakm/dev/pyimgui
    Complete output from command python setup.py egg_info:
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        """
        cimgui.EndMenu()
    
    
    def menu_item(
        str name, str shortcut=None, cimgui.bool selected=None, enabled=True
                                                         ^
    ------------------------------------------------------------
    
    imgui/core.pyx:2029:54: Cannot assign None to bool
    Compiling imgui/core.pyx because it depends on /Users/swistakm/.envs/pyimgui/lib/python2.7/site-packages/Cython/Includes/libcpp/__init__.pxd.
    [1/1] Cythonizing imgui/core.pyx
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/swistakm/dev/pyimgui/setup.py", line 146, in <module>
        compiler_directives=compiler_directives, **cythonize_opts
      File "/Users/swistakm/.envs/pyimgui/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1026, in cythonize
        cythonize_one(*args)
      File "/Users/swistakm/.envs/pyimgui/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1146, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: imgui/core.pyx
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/swistakm/dev/pyimgui/
```

It fortunately still builds on previous releases (till 0.27.3). pyimgui is mostly distributed as a built wheel so the problem isn't that critical but it would be nice to fix it soon.

**Comment by pconerly** [comment]
We can close this issue now :D

**Comment by swistakm** [comment]
Released as `0.1.0`
